name: Deploy project plan to heroku

on:
  push:
    branches: [ master ]

jobs:
  build-backend:
    name: build jar file
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: download frontend build artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven into target folder
        run: mvn -B package --file ./backend/pom.xml
      - name: upload backend.jar file
        uses: actions/upload-artifact@v2
        with:
          name: backend.jar
          path: backend/target/backend.jar